create database customer_behavior;
use customer_behavior;

-- what is total revenue generated by male vs female cx?
select gender, SUM(purchase_amount) as revenue
from customer group by gender;

-- which cx used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer 
where discount_applied  = 'Yes' and  purchase_amount>=(select avg(purchase_amount) from customer);


-- which are top 5 products with highest average review rating
select item_purchased , Round(Avg(review_rating),2) as Avg_review_rating
from customer
group by item_purchased
order by  Avg_review_rating desc 
limit 5;

-- Compare avg Puchase Amounts between Standard and Express Shipping
select shipping_type,
Round(avg(purchase_amount),2) as Avg_Amount
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Do subscribed customers spend more? Compare average spend and total revenue between subsriber and non subsriber
select subscription_status, 
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as Avg_Purchase_amount,
sum(purchase_amount) as Revenue
from customer
group by subscription_status
order by Revenue desc;

-- which top 5 products have highest percentage of purchase with discounts applied?
select item_purchased ,
ROUND(SUM(case when discount_applied = 'Yes' then 1 else 0 end)/count(*) * 100,2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
select customer_id, previous_purchases,
case 
	when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from customer
)

select customer_segment, count(*) as Number_of_Cx
from customer_type
group by customer_segment;


-- What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           row_number() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select  subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status;

-- What is the revenue contribution of each age group? 
select age_group, sum(purchase_amount) as revenue
from customer
group by age_group
order by revenue desc;

SELECT VERSION();